### ISSUE TITLE
Store data in a table with a composite key

### ISSUE THREAD

**Issue by andries-devwork** [andries-devwork/serverless#17]
Data is stored in a table with a composite key.

1:M (1 to many) relationship between users and TODO items is modeled using a DynamoDB table that has a composite key with both partition and sort keys. Should be defined similar to this:

```yaml
   KeySchema:
      - AttributeName: partitionKey
        KeyType: HASH
      - AttributeName: sortKey
        KeyType: RANGE
```
